name: mana_eventbus_trigger
resolution: workspace
description: "Mana Eventbus Trigger plugin"
version: 1.0.0
homepage: https://github.com/lhlyu/flutter_mana
repository: https://github.com/lhlyu/flutter_mana

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  mana: ^1.0.0
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
