name: mana
description: "Mana is an in-app debug kits platform for Flutter. Flutter应用内调试工具平台"
version: 1.0.0
homepage: https://github.com/charles0122/flutter_mana
repository: https://github.com/charles0122/flutter_mana
documentation: https://github.com/charles0122/flutter_mana
issue_tracker: https://github.com/charles0122/flutter_mana/issues
topics: [ debug, in-app-debug, diagnostics, plugin ]
resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.3
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

