name: mana
publish_to: none
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

# workspace:
#   - packages/mana
#   - packages/mana_align_ruler
#   - packages/mana_color_sucker
#   - packages/mana_device_info
#   - packages/mana_dio_inspector
#   - packages/mana_fps_monitor
#   - packages/mana_grid
#   - packages/mana_license
#   - packages/mana_log_viewer
#   - packages/mana_memory_info
#   - packages/mana_package_info
#   - packages/mana_screen_info
#   - packages/mana_shared_preferences_viewer
#   - packages/mana_show_code
#   - packages/mana_touch_indicator
#   - packages/mana_visual_helper
#   - packages/mana_widget_info_inspector

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^7.3.0
