name: mana_database
description: "Mana Database plugin"
resolution: workspace
version: 1.0.0
homepage: https://github.com/lhlyu/flutter_mana
repository: https://github.com/lhlyu/flutter_mana

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  mana: ^1.0.0
  material_table_view: ^5.5.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  translator: ^1.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
