name: mana_device_info
description: "Mana Device Info plugin"
version: 1.0.0
homepage: https://github.com/charles0122/flutter_mana
repository: https://github.com/charles0122/flutter_mana

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_mana: ^1.0.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0