name: mana_show_code
description: "Mana Show Code plugin"
version: 1.0.0
homepage: https://github.com/charles0122/flutter_mana
repository: https://github.com/charles0122/flutter_mana
resolution: workspace
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"


dependencies:
  flutter:
    sdk: flutter
  mana: ^1.0.0
  vm_service: ^15.0.2
  string_scanner: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
